#!/bin/sh

# WordPress Root, PHP and Composer Dependencies
composer run predeploy

# Theme Dependencies
# TODO: Fix linting issues, prevent push if it doesn't pass
# cd 'wp-content/themes/access/'
# npm run predeploy
