<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WPML_Auto_Loader' => $vendorDir . '/wpml/commons/src/wpml-auto-loader.php',
    'WPML_Dependencies' => $vendorDir . '/wpml/commons/src/dependencies/class-wpml-dependencies.php',
    'WPML_Twig_WP_Plugin_Extension' => $vendorDir . '/wpml/commons/src/twig-extensions/wpml-twig-wp-plugin-extension.php',
    'xrstf\\Composer52\\AutoloadGenerator' => $vendorDir . '/xrstf/composer-php52/lib/xrstf/Composer52/AutoloadGenerator.php',
    'xrstf\\Composer52\\Generator' => $vendorDir . '/xrstf/composer-php52/lib/xrstf/Composer52/Generator.php',
);
